name: lingtistudio

version: "3.9"

services:
  lingtistudio:
    build:
      context: .
      dockerfile: Dockerfile
    image: lingtistudio:latest
    container_name: lingtistudio
    restart: unless-stopped
    ports:
      - "3000:3000"
      - "8000:8000"
    volumes:
      - ./configs:/app/configs
      - ./data:/app/data
    environment:
      - PILIPILI_CONFIG=/app/configs/config.yaml
      - PORT_FRONTEND=3000
      - PORT_API=8000
